name: Deploy on Enviroment Dev
on:
  pull_request:
    branches:
      - 'master'
      - 'developement'
    types:
      - closed
jobs:
  test_preview:
    runs-on: self-hosted
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Build bunx
        run: |
          echo "Bun is Building"
          sudo rm -rf /var/www/ie106
          sudo cp -r /home/ubuntu/ie106-front-end/_work/ie106-front-end/ie106-front-end/dist/ /var/www/ie106/
